In [5]:
import numpy as np
arr = np.ones((2, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
np.ones((2, 4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [9]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
np.random.rand(3, 2)

array([[0.22537182, 0.62907136],
       [0.9722968 , 0.16397269],
       [0.75681717, 0.58533873]])

In [11]:
np.random.randn(3, 2)


array([[ 1.06704038, -1.1253918 ],
       [-0.70322759, -0.63765244],
       [-0.15517116,  0.43882815]])

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [14]:
# 1D Arrays
arr = np.array([1, 2, 3, 4, 5])
arr[0]

arr[1:4]
arr[::2]

array([1, 3, 5])

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]
arr[:, 1]
arr[1, :2]

array([4, 5])

In [17]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]

array([4, 5])

In [18]:
# Reshape
arr = np.arange(6)
arr.reshape(2, 3)

# Concatenation
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))

# Stacking
np.vstack((a, b))
np.hstack((a, b))

array([1, 2, 3, 4])

In [19]:
arr = np.arange(6)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)

[5 7 9]


In [21]:
print(a*b)

[ 4 10 18]


In [22]:
print(a-b)

[-3 -3 -3]


In [23]:
a*b

array([ 4, 10, 18])

In [24]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [25]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [26]:
A @ B

array([[19, 22],
       [43, 50]])

In [27]:
arr = np.array([1, 2, 3, 4])
arr.sum()

np.int64(10)

In [28]:
arr.mean()

np.float64(2.5)

In [29]:
arr.max()

np.int64(4)

In [30]:
arr.min()

np.int64(1)

In [31]:
arr.std()

np.float64(1.118033988749895)

In [32]:
arr = np.array([1, 2, 3, 4, 5])
arr[0]

np.int64(1)

In [33]:
arr[1:4]

array([2, 3, 4])

In [34]:
arr[::2]

array([1, 3, 5])

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]

np.int64(2)

In [37]:
arr[:, 1]

array([2, 5])

In [38]:
arr[1, :2]

array([4, 5])

In [41]:
arr = np.array([1, 2, 3, 4, 5])

In [43]:
mask = arr > 3
arr[mask]

array([4, 5])